# Reference URL: https://docs.docker.com/compose
version: '3.9'

services:
  sappio_app:
    image: sappio_app
    container_name: sappio_app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    env_file:
      - ./.env.docker
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm start
    stop_grace_period: 1s

networks:
  backend:
