# Reference URL: https://docs.docker.com/compose
version: "3.9"

services:
  sappio_db:
    image: postgres:14.5
    networks:
      - backend
    restart: always
    env_file:
      - ./.env.docker
    environment:
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_USER: ${DB_USER}
      POSTGRESQL_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    stop_grace_period: 1s
    

  sappio_app:
    image: node:16.18.1
    networks:
      - backend
    container_name: sappio_app
    env_file:
      - ./.env.docker
    restart: on-failure:10
    depends_on:
      - sappio_db
    ports:
      - 3000:80
    command: bash -c "npm run docker:init"
    stop_grace_period: 1s

networks:
  backend:

volumes:
  db-data: