# This is a basic workflow to help you get started with Actions
name: Cron rest Job

# Controls when the workflow will run
on:
  # Triggers the workflow every day minutes
  schedule:
  
    - cron: "00 10 * * 6,7"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a command using the runners shell
      - name: Run a script
        run: |
          echo "It's not time to make a change. Just relax, take it easy."
          echo "You're still young, that's your fault. There's so much you have to know"

