# This is a basic workflow to help you get started with Actions
name: Cron CI

# Controls when the workflow will run
on:
  # Triggers the workflow every day minutes
  schedule:
    - cron: "1 10 * * 6,7"
    - cron: "1 10 * * 1,2,3,4,5"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run working script

        if: github.event.schedule != '1 10 * * 1,2,3,4,5'
        run: echo "Wake up! Grab a brush and put a little makeup"

      - name: Run resting script
        if: github.event.schedule != '1 10 * * 1,2,3,4,5'
        run: echo "It's not time to make a change! Just relax, take it easy."
