# This is a basic workflow to help you get started with Actions
name: Cron CI

on:
  schedule:
    - cron: '0 10 * * 1-5'  # Run on weekdays
    - cron: '0 10 * * 6,0'  # Run on weekends

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Run weekday script
        if: github.event.schedule != '0 10 * * 6,0'
        run: echo "Wake up! Grab a brush and put a little makeup"

      - name: Run weekend script
        if: github.event.schedule == '0 10 * * 6,0'
        run: echo "It's not time to make a change! Just relax, take it easy."
