name: Run ESLint on Pull Requests

on:
  - pull_request

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 42
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # Check out the repository
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      # Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install your dependencies
      - run: npm ci --legacy-peer-deps

      # Install ESLint
      - run: npm install eslint --save-dev

      # Run ESLint
      - run: npx eslint .
